### ISSUE TITLE
Stopped working after High Sierra upgrade

### ISSUE THREAD

**Issue by jkomara** [brycekahle/sudolikeaboss#2]
I upgraded to High Sierra and am running 1password 6.8 with iTerm2 Build 3.1.5.beta.2.

I tried both ravenac95 and this one. I can see the two arrows in the corner of the iTerm2 window but there is no pop up. Is there a known issue with High Sierra?

**Comment by brycekahle** [comment]
What is your full version? If it is 6.8.1 or later, it will not work period. See #1

**Comment by brycekahle** [comment]
I have High Sierra btw and it functions with 6.8 just fine.

**Comment by jkomara** [comment]
1Password 6
Version 6.8 (680015)
AgileBits Store

I had just upgraded and some other issues with High Sierra so I wanted to check. I use this all the time and it is killing me right now to not have it. :(

**Comment by jkomara** [comment]
I appreciate you getting back to me as quickly as you did. I will post back here if I figure out what I did wrong.

**Comment by brycekahle** [comment]
Have you run `sudolikeaboss register`?

**Comment by jkomara** [comment]
That was it!! Thank you!!!! 😄

**Comment by brycekahle** [comment]
Great!
